name: Deploy to Niagahoster

on:
  push:
    branches:
      - master  # atau branch lain yang kamu gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Niagahoster
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update -y
          sudo apt-get install lftp -y
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD ftp.bukitakasia.com; mirror -R build/ /public_html/Public-coba"
