name: Deploy to Niagahoster FTP

on:
  push:
    branches:
      - master  # Ganti dengan branch yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ftp://153.92.11.88  # Ganti dengan FTP server kamu
        username: ${{ secrets.FTP_USERNAME }}  # Ganti dengan username FTP kamu
        password: ${{ secrets.FTP_PASSWORD }}  # Ganti dengan password FTP kamu
        local-dir: ./dist  # Direktori hasil build
        git-ftp-args: --insecure --syncroot /public_html/Project-coba  # Menambahkan opsi ini untuk menghindari error SSL dan menentukan direktori tujuan di server FTP
